#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan  6 12:15:11 2022

@author: shaunogrady
"""

import time
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

params = {
    'n_estimators': [200, 500],
    'max_depth': [4,6,8],
    'criterion': ['gini']
}

classifier = RandomForestClassifier()

gridsearch = GridSearchCV(classifier, params, cv=5, n_jobs=-1, verbose=6)

X_res = pd.read_csv('X_train_pca_rus.csv')
y_res = pd.read_csv('y_train_pca_rus.csv')
X_res.pop('Unnamed: 0')
y_res.pop('Unnamed: 0')

start_time = time.time()
rnd_frst_clf = gridsearch.fit(X_res, y_res)

end_time = time.time()


print("The grid search random forest training time is: {} hours".format((end_time - start_time)/3600))

bestParameters = rnd_frst_clf.best_params_

print(bestParameters)


import joblib

joblib.dump(rnd_frst_clf, "pca_rus_gs_rndFrst_model.pkl")

